### ISSUE TITLE
Duplicated scraped documents in JSONs

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#104]
I found several duplicates of the data scraped

e.g. for MSF 20190117.json
11 occurrences of ad6a1c16d161c6989d2d7a2d793b5c0a
21 occurrences of 43715f478bd1621b8f8aecf2ac693ea4
11 occurrences of 66c46a148bccf91aba7be09e431fde74

and for MSF 20190131.json
13 occurrences of ad6a1c16d161c6989d2d7a2d793b5c0a
24 occurrences of 43715f478bd1621b8f8aecf2ac693ea4
13 occurrences of 66c46a148bccf91aba7be09e431fde74

If the same data is scraped from them multiple times then it wont give us invalid results, but is a waste of time to process the same data multiple times. 
However, if different data is scraped then we may have issues since the output files will be replaced rather than updated (so could potential replace correct match data with no matches).

Thus the urgency of this fix is dependant on whether the former or latter situation is occurring.

**Comment by hblanks** [comment]
My reckoning is that this will be Overcome By Events as the new scraping tasks, which include a manifest of all scraped PDF files, roll out.

But, it may not. So, we should keep this open as a bug and revisit it next month.

**Comment by nsorros** [comment]
Leaving this open @hblanks since this is not related to the database and needs to be addressed at some point

**Comment by lizgzil** [comment]
I hope fixed in https://github.com/wellcometrust/reach/pull/319
