### ISSUE TITLE
Questions from Gates foundation

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/reach#110]
Hi @hblanks and @SamDepardieu,

These questions came up during our conversation with Gates and I remember it coming up again previously. The questions are:
* Why Unicef has so few documents? and similar for NICE.
* Which years is the tool picking up from the sources?

In regards to the number of documents, this is picked up from my presentation. I have also noticed that the numbers for example for WHO are significantly less tha the number of documents in the iris webpage, so I was wondering whether this has to do with documents only appearing in the database if they have a reference section. I am attaching some screenshots for the numbers I and Gates is reffering to. 
<img width="293" alt="Screen Shot 2019-04-08 at 3 48 17 PM" src="https://user-images.githubusercontent.com/4975761/55733481-ce17f380-5a15-11e9-90ec-2ec3798d21b8.png">
<img width="657" alt="Screen Shot 2019-04-08 at 3 48 05 PM" src="https://user-images.githubusercontent.com/4975761/55733513-da03b580-5a15-11e9-9db4-877b097b86fc.png">

In regards to the second, they are wondering whether we only pick up documents from certain years. As far as I am aware, we pick up documents from all years available but I might be wrong.

**Comment by SamDepardieu** [comment]
@nsorros We're picking WHO docs from 2012 to 2019

For UNICEF, the number of results is a bit more worrying, I'll check and come back to you

**Comment by nsorros** [comment]
Thanks for the response @SamDepardieu. What about the years for other policy organisations?

**Comment by SamDepardieu** [comment]
| Organisation | Publication | Years |
 |--------------|------------|-------|
 | WHO             | Everything on apps.who.int/iris | 2012 - 2019 |
 | NICE             | All the Guidances and evidences | 2000 - 2019 |
 | MSF              | All the reports and activity reports | 2007 - 2019 |
 | GOV             | Everything from gov.uk/government/publications | 1945 - 2019 |
 | UNICEF        | Everything from data.unicef.org/resources/resource-type/[publications and guidance] | 2010 - 2019 |
 | Parliament   | Everything from search-material.parliament.uk | 1984 - 2019 |

**Comment by SamDepardieu** [comment]
Also added this to the readme, as it looked like something useful

**Comment by nsorros** [comment]
Really helpful @SamDepardieu, thanks.

**Comment by nsorros** [comment]
I will keep this open until we find what happened with Unicef

**Comment by nsorros** [comment]
I am closing this but @dd207 should be aware
