### ISSUE TITLE
Keywords and Researchers list as input to the policy tool

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/reach#118]
At the moment the policy tool accepts a list of publications as an input while the keywords the scraper matches is a file in the tool and there is no input for list of researchers to match.

To address some asks from our users and in particular our with Bill and Melinda Gates foundation we would need to be able to provide to the tool a set of keywords as well as a set of researchers to match. The keywords would be similar to the part where the scraper looks for words such as Wellcome but it will provide the file as an input while the researchers is new functionality totally that we need to build which will look, to begin with, for exact matches of researchers named in the references sections and the full text.

As we build that functionality, it would be good to scope providing these files as input to the policy tool so that it would be easier to integrate with what we will build.

**Comment by SamDepardieu** [comment]
This shoudn't be too much of an issue, as the tool is already fed a file for the keywords. Researcher names are just keywords as well, if you feed them as keywords, the tool will look for them the same way

**Comment by nsorros** [comment]
Good to know @SamDepardieu. As I mentioned in my comment in the product meeting there are two reasons we need this. First we want to be able to manually run the tool with an altered list, not add to the list and when the tool runs next time get the data and secondly we want to start building functionality that will move us away from exact matches which is what the keywords do so to do that we will possibly need more information about what they keyword represents, hence the different file for researcher but we can also do by tweeaking the current keywords file to add more metadata for each "keyword"

**Comment by nsorros** [comment]
I am of the opinion that is in @dd207 plans to be addressed in some way. The idea here was to differentiate between researchers and other search terms when running the tool ourselves but since we are not doing that now i guess there will an interface way to differentiate if needed
