### ISSUE TITLE
Add additional data from WHO iris

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/reach#120]
Hi @SamDepardieu,

In continuation of the issue about whether we scrape bulletin journals and some metadata from WHO iris, I would like to request for some additional data to be included in the scrape.

I would like to add the **publisher** information even though I am unsure to how it differs from author but just to make sure we capture the information about the country offices and which part of WHO the document is coming from.

I would also like to add the language information as our tools work in English documents so it is important to know which subset is analyzable but at the same time research whether some of the tools work even though not explicitly trained in non English documents.

My understanding is that we include subject information since I did use that information to train the tagger, is it not from the metadata? In any case, maybe getting from the metadata is a more sustainable strategy.

Lastly, even though in metadata, can we add the collections information from the item record, you can see an example here https://apps.who.int/iris/handle/10665/272359. In the example the collection is **Country offices**.

@lizgzil, anything you would like to add?

**Comment by lizgzil** [comment]
In regards to the publisher information, I'm not 100% what `dc.coverage.spatial` is, but from the looks of things it might be the location where the document was published/written (e.g. this doc about Iran has Geneva https://apps.who.int/iris/handle/10665/272742?show=full, but the doc you linked to about Ethiopia says Addis Ababa https://apps.who.int/iris/handle/10665/272359?show=full). This might help us to understand our biases towards research in the global north? Might be worth finding out what this metadata is to see if it's useful in our ethical considerations.

**Comment by nsorros** [comment]
I think this is for @dd207 to prioritise or close now

**Comment by jdu** [comment]
The metadata for a lot of these files is inconsistent as well, I've been seeing a lot of PDFs where the author, publisher, etc... from the PDF metadata is actually describing the software application which generated the document versus the actual authority or organisation so there will have to be some deeper thinking on how we get this information if we're going to implement this.
