### ISSUE TITLE
References file starting with 'file://' throws error

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/reach#124]
At the moment we instruct the user to pass a references file that is local using the `file://` notation, for example:
```
python ./refparse.py \
    --scraper-file "s3://datalabs-data/scraper-results/msf/20190117.json" \
    --references-file "file://./references_folder/references_file.csv" \
    --model-file "s3://datalabs-data/reference_parser_models/reference_parser_pipeline.pkl" \
    --output-url "file://./tmp/parser-output/output_folder_name"
```

This functionality is not implemented for any url other than the output at the moment. The way other files are loaded are, if the url starts with `s3://` then it goes to s3 otherwise it assumes local.

We have two options and I am unsure which is the best. One is to change the Readme to reflect the way the code works now, i.e. dropping the prefix `file://` and the other to implement looking locally when url starts with `file://`. @hblanks any thoughts?

**Comment by hblanks** [comment]
Yeah, this was a thorn at the time of implementing. To restate it, if a tad differently, we could:

1. Change the names to `model-url`, etc, and make them all support require URLs, either as file:// or s3://, or
2. Change `output-url` to `output` and let that either take an S3 URL or a path

I prefer (2). If that sounds reasonable to you.

Added to the stack for the coming sprint, https://trello.com/c/vcRu2eId/694-standardize-file-arguments-to-refparsepy

**Comment by nsorros** [comment]
Sounds good 👍 Thanks for the quick response @hblanks

**Comment by hblanks** [comment]
@nsorros  - looking over this again, actually, would it be OK if the tool only wrote output to local disk? It seems like it may be best to let the tool always write to local disk, and then the data scientist could upload it where she sees best, using whatever tool works best. What do you think?

If so, we would change `output-url` to `output-dir` and be done.

**Comment by nsorros** [comment]
sounds good 👍

**Comment by nsorros** [comment]
i think we are not using the file convention anymore
