### ISSUE TITLE
Policy tool output does not contain organisation name

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/reach#126]
At the moment when we run the policy tool the organization name is not included in the output file.

The only proxy to an organisation is the document url at the moment which when running the policy tool for WHO, UNICEF, MSF and NICE and after processing the url to keep the part between the http and first forward slash returns the following unique values: 'apps.who.int', 'www.nice.org.uk', 'www.msf.org.uk', 'www.fao.org', 'www.unicef.org', 'data.unicef.org'. Most of those values are straightforward to map to their original organisation but for example fao.org requires further investigation.

I propose we add this information in the output and ideally moving forward start producing most of the files we persist as we can share them easily with no extra steps with the users that are asking for the data each time.

**Comment by jdu** [comment]
@nsorros I think we're doing this now no? Can we close this issues?

**Comment by dd207** [comment]
Agree that we are pulling through the organisations names now so will close.
