### ISSUE TITLE
the hard text search isn't working in refparse

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#162]
Looking in `refparse`:
```
def run_match(structured_references, fuzzy_matcher, text_matcher):
    matched_references_parser = fuzzy_matcher.fuzzy_match(
        structured_references
    )
    matched_references_hard_text = text_matcher.hard_text_search(
        doc
    )
    matched_references = remove_dups_and_concat(matched_references_parser, matched_references_hard_text)
    return matched_references
```

it complains because it doesn't know what `doc` is. So I changed `doc` to `structured_references`, and it complained because the input to `hard_text_search` ( scraped_text) needs to have `scraped_text.section` and `scraped_text.id` fields.

I think `hard_text_search` needs to be restructured to input `structured_references`.

Didn't have time to investigate further, but wanted to get an issue open.

**Comment by nsorros** [comment]
I am aware of this and will be fixed as part of my PR. This was introduced during the refactoring.

**Comment by lizgzil** [comment]
I think irrelevant and possibly fixed now
