### ISSUE TITLE
Investigate why there are duplicate ref matches found in the same policy document

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#183]
Duplicate reference found even though no duplicate found in policy document.

A citation for "Trends in adult body-mass index in 200  countries from 1975 to 2014: a pooled analysis of  1698 population-based measurement studies with   1377-1396" only occurred once in a policy document (http://www.fao.org/3/I9553EN/i9553en.pdf), but the Reach output said it came up twice.

the tool also said it came up twice in
https://www.unicef.org/publications/files/State_of_Food_Security_and_Nutrition_in_the_World_2017.pdf
but it only occurs once.

"Disability-adjusted life years (DALYs) for 291 diseases and injuries in 21 regions, 1990‚Äì2010: a systematic analysis for the Global Burden of Disease Study 2010" is said to come up twice in 
https://apps.who.int/iris/bitstream/handle/10665/144099/Early%20Child%20Development%20in%20the%20European%20Region%20needs%2c%20trends%20and%20policy%20development.pdf?sequence=1&isAllowed=y
but it actually only comes up once.

## November update:

Just to note that this is still an issue. I ran the exact matcher using the policy dag and got 7 or 9 duplicate matches for each match.
![Screenshot 2019-11-08 at 14 53 55](https://user-images.githubusercontent.com/15956065/68485682-a309b280-0237-11ea-9525-6cc7f11e38ea.png)

Looking into this issue more I printed the results of the elastic search when there was a match found, and I see that there are indeed the same policy doc hashes but with different ES indices.

e.g. here is an example of the matches found when searching for one EPMC publication title in the text of policy documents:
```
title = publication['title']

        # Exclude short titles that create noisy matches
        if len(title) < self.title_length_threshold:
            return

        body = {
            "query": {
                "match_phrase": {
                    "doc.text": title
                }
            },
            "_source": ["doc.hash"],

        }
        res = self.es.search(
            index=self.es_full_text_index,
            body=body,
            size=1000 # if there are more than 1000, need to paginate
        )
```
```
'hits': 
[{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'aXpUQW4BiUIv3WUbqiOh', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': 'zXpkQW4BiUIv3WUbwia0', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': 'DwgzQW4BpEOiqNaE-CPg', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}, 
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'EUnQQW4Bc-nJDJpI74RO', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': 'KkefQW4BKSZwVCAUPoCh', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}, 
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'y0ecQW4BKSZwVCAUfH4A', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': '1zJzS24BYnrMilTDznnO', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}, 
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'o2TqQW4BeRBY61-vNjAA', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': '5x1oRW4BBrdDKXWtLI2K', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'Fh1qRW4BBrdDKXWt149I', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}]
```
It's quite annoying since the exact matcher already takes a long time, so we could do with some deduplication before exact matching rather than after.

## January update:

I looked into where the problem was occuring by running each of the airflow tasks in turn and looking for duplications.

### Fuzzy matcher (output has duplication):
I ran `./docker_exec.sh airflow test policy-test FuzzyMatchRefs.nice 2020-01-6`, but found no matches. I changed the thresholds (SHOULD_MATCH_THRESHOLD and SCORE_THRESHOLD) to 0. I also set `spider_years` to `list(range(2012, datetime.datetime.now().year + 1))` and `item_limits` to `ItemLimits(None, None)` (i.e. the main policy dag settings). With these changes I found 1370 matches in 1409 references.

Despite the changes to the parameters in this analysis, there still shouldn't be any duplication in the results.

Of the matches found, there are 584 unique 'match_pmid' - 'policy_doc_id' pairs, 368 of which have 2-4 repeats. The same result is found if you look for unique 'match_pmcid' - 'policy_doc_id' pairs

### Extract references (output has duplication):
I ran `./docker_exec.sh airflow test policy-test ExtractRefs.nice 2020-01-6` and found 1409 references.
Of these there were 945 unique 'Reference id's, and 47 unique 'Document id's and 998 unique 'Reference id' - 'Document id' pairs.

### Parse references (no duplication, but duplication in the sections text!):
I ran `./docker_exec.sh airflow test policy-test ParsePdf.nice 2020-01-6`.
of the 143 documents found I also got 143 unique document file hash. However, when you look at the sections text some of it is repeated (the case I looked at was for [this document](https://www.nice.org.uk/guidance/ph31/resources/unintentional-injuries-on-the-road-interventions-for-under-15s-pdf-1996292434885) where there is only one reference by Racioppi but the sections text had 2).
I realised the issue was in grab_sections and have fixed it in https://github.com/wellcometrust/reach/pull/319

After this change, the fuzzy matcher task for NICE returns 961 matches (before this was 1370), where there are 19 repeats of `reference_id`- `policy_doc_id` pairs (before this was 377).
Thus there is still some duplication.

**Comment by nsorros** [comment]
That will require some time to figure out and it might solve itself in the future. I suggest we keep an eye for it and if it appears again we spend some time to understand it.

**Comment by lizgzil** [comment]
Just to note that this is still an issue. I ran the exact matcher using the policy dag and got 7 or 9 duplicate matches for each match.
![Screenshot 2019-11-08 at 14 53 55](https://user-images.githubusercontent.com/15956065/68485682-a309b280-0237-11ea-9525-6cc7f11e38ea.png)

Looking into this issue more I printed the results of the elastic search when there was a match found, and I see that there are indeed the same policy doc hashes but with different ES indices.

e.g. here is an example of the matches found when searching for one EPMC publication title in the text of policy documents:
```
title = publication['title']

        # Exclude short titles that create noisy matches
        if len(title) < self.title_length_threshold:
            return

        body = {
            "query": {
                "match_phrase": {
                    "doc.text": title
                }
            },
            "_source": ["doc.hash"],

        }
        res = self.es.search(
            index=self.es_full_text_index,
            body=body,
            size=1000 # if there are more than 1000, need to paginate
        )
```
```
'hits': 
[{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'aXpUQW4BiUIv3WUbqiOh', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': 'zXpkQW4BiUIv3WUbwia0', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': 'DwgzQW4BpEOiqNaE-CPg', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}, 
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'EUnQQW4Bc-nJDJpI74RO', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': 'KkefQW4BKSZwVCAUPoCh', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}, 
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'y0ecQW4BKSZwVCAUfH4A', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': '1zJzS24BYnrMilTDznnO', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}, 
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'o2TqQW4BeRBY61-vNjAA', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
 {'_index': 'policy-test-docs', '_type': '_doc', '_id': '5x1oRW4BBrdDKXWtLI2K', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}},
{'_index': 'policy-test-docs', '_type': '_doc', '_id': 'Fh1qRW4BBrdDKXWt149I', '_score': 19.55179, '_source': {'doc': {'hash': '42db3dd8b3156d81c60378bf0e52350d'}}}]
```
It's quite annoying since the exact matcher already takes a long time, so we could do with some deduplication before exact matching rather than after.

**Comment by jdu** [comment]
This may have been down when the index is created it wasn't targeting the doc.organisation correctly when clearing previous citations and may be fixed by some changes in #316

**Comment by lizgzil** [comment]
will investigate in the new year to see if it's still happening 👍

**Comment by nsorros** [comment]
could we have a look at this? as this keeps happening maybe now is a good time to have a good idea of what is going on so that we can put it behind us.

**Comment by jdu** [comment]
@nsorros I think this is probably resolved by the updates I merged in before x-mas, we haven't deployed that to production as of yet though and in order to see it resolved you would need to clear all the data in elastic in your local runs.

**Comment by lizgzil** [comment]
@jdu FYI there are some comments from my analysis in the description now. In short - extracting the references seems to be where the duplication is introduced
