### ISSUE TITLE
The exact matcher is only used in reference section texts

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#202]
At the moment we have
```
sectioned_documents = transform_scraper_file(scraper_file)
exact_matcher = ExactMatcher(sectioned_documents, 
     settings.MATCH_TITLE_LENGTH_THRESHOLD)
```
in `refparse`, but actually for the exact matching _I think_ we should
1. search in **all** the pdf text
2. search regardless of whether the pdf has a references section or not.

**Comment by nsorros** [comment]
Indeed. The intention has always been to open exact matching to the entire pdf. One thing to keep in mind when we decide to do that is to evaluate how well the matches are on a sample to get a feel of the noise introduced.
