### ISSUE TITLE
(Make available and) Document loading refparser test data from S3

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#22]
There is none of the data needed in this repo to test the reference parser, so we need to add:

- Makefile
- README with instructions of how to download data
- Data in suitable place in S3

At the moment the test data needed is here https://s3.console.aws.amazon.com/s3/buckets/datalabs-data/reference_parser/data/raw/?region=us-east-2&tab=overview

of these files, for testing we need:
- `actual_number_refs_sample.csv`
- `actual_reference_structures_sample.csv`
- `Positive_and_negative_publication_samples.csv`

**Comment by hblanks** [comment]
Yes! We can prioritize this.

Also: though it was hard for me to tell at first, this is, indeed, a bug because you either can't test the parser locally, or (also possible) it's not yet clear to all of us how to do so. @SamDepardieu , please do characterize this a bit if you get a chance, and we'll add a card for it.

**Comment by SamDepardieu** [comment]
We should definitly provide some data to let users test the parser. There's two options: 
 - Provide real data, but then we need to make sure what we provide comes from public data
 - Provide auto-generated data, in which case we need to generate it (and to make it clear that it is fake data)

In both case we could probably just host it on S3 and make it public, in my opinion

**Comment by hblanks** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document loading refparser test data from S3](https://trello.com/c/vQ9twBVz/550-document-loading-refparser-test-data-from-s3)

**Comment by lizgzil** [comment]
not relevant anymore with end to end tests
