### ISSUE TITLE
Add publication identifiers to citations JSON

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#271]
We currently have this in `reach/reach/airflow/tasks/fuzzy_match_refs.py` :
```
return {
                'Document id': reference['Document id'],
                'Reference id': reference['Reference id'],
                'Extracted title': reference['Title'],
                'Matched title': matched_reference['doc']['title'],
                'Similarity': best_score,
                'Match algorithm': 'Fuzzy match'
            }
```

resulting in JSON of the format:

```json
{
  "Document id": "ce0c7bc7e5204fa4018b4c10be4bcc8e",
  "Reference id": 1926908462195528000,
  "Extracted title": "The spectrum of engagement in HIV care and its relevance to test-and-\ntreat strategies for prevention of HIV infection",
  "Matched title": "The spectrum of engagement in HIV care and its relevance to test-and-treat strategies for prevention of HIV infection.",
  "Similarity": 65.7951,
  "Match algorithm": "Fuzzy match"
}
```

But we should also include whatever unique identifiers are present, (EPMC reference (['doc']['doi'] and ['doc']['pmid'] would be good).

**Comment by nsorros** [comment]
Indeed, that seems odd, I probably forgot to include it when implementing this task :S

**Comment by lizgzil** [comment]
I assume we'll need both doi and pmid to make sure we have at least one unique identifier - @aCampello does this make sense based on your work looked for abstracts in EMPC? I know you said something about coverage of both of these

**Comment by aCampello** [comment]
Correct, I am not sure that the DOI is a good unique identifier from EPMC publications. By downloading the EPMC data from s3 and checking for dois, I found that 79% of the DOIS exists whereas 89% of the PMIDS exist. The PMCids where the most consistent of them (they exist for all indexes).

```bash
# tmpvr66zjc9s is the file obtaining by downloading the epic-metadata from s3
with open('Downloads/tmpvr6zjc9s') as f:
    json_lines += [json.loads(line) for line in f]

existing_dois = 0
for line in json_lines:
    existing_dois += line.get('doi') is not None

existing_pmids = 0
for line in tqdm.tqdm(json_lines):
    existing_pmids += line.get('pmid') is not None

existing_pmcids = 0
for line in tqdm.tqdm(json_lines):
    existing_pmcids += line.get('pmcid') is not None
```

outputs, in percentage:

DOIS: 0.7923515595801558, PMIDS: 0.8952600631649221, PMCIDS: 1.0

**Comment by hblanks** [comment]
If we can, best would be to include all 3.

If CrossRef gets incorporated as another publication source, there will be many pubs that have DOIs but no PMIDs / PMCIDs.

**Comment by hblanks** [comment]
(note also this is queued up for next sprint at https://trello.com/b/igCne4h5/data-labs-sprint)

**Comment by ivyleavedtoadflax** [comment]
This will be resolved in https://github.com/wellcometrust/reach/pull/314.

**Comment by nsorros** [comment]
> This will be resolved in #314.

I don't think this resolves it because it does not change the indexed data in ES. This is only for local runs.

**Comment by ivyleavedtoadflax** [comment]
Ahh sorry i misunderstood!

**Comment by jdu** [comment]
I'm in the midst of refactoring some pieces to normalize the citations and full-text index data, once that's done I can loop back and pull any ids we have access to into the indexes as well.

**Comment by ivyleavedtoadflax** [comment]
I know this is probably the wrong place to say this, but just to flag @jdu, it would be super useful to capture the provider in this JSON too, if its not captured already.

**Comment by jdu** [comment]
@ivyleavedtoadflax As in that it's coming from EPMC? Or the publication name? I can definitely tag it as sourced from EPMC, the publication, authors, pub year, etc... are already set up in my branch to populate into ES.

**Comment by ivyleavedtoadflax** [comment]
as in its coming from govuk, parliament, etc

**Comment by jdu** [comment]
doi, pmid, pmcid are stored in citations as of #316 and will be in place once that reaches production as well as organisation.

**Comment by nsorros** [comment]
@jdu @ivyleavedtoadflax just a reminder to possibly open a separate issue for the provider request.

**Comment by jdu** [comment]
@nsorros These were resolved in the code that's been merged into master before x-mas.
