### ISSUE TITLE
Download CSV button in reach results page isn't wired

### ISSUE THREAD

**Issue by jdu** [wellcometrust/reach#280]
It looks like this button isn't wired to anything:

![Screenshot 2019-11-13 at 12 09 19](https://user-images.githubusercontent.com/120225/68762797-cdc88200-060e-11ea-971a-ee0d0799ffce.png)

If this isn't supposed to be wired yet can we hide it for now at least so that we don't get a load of false reports that it's not working?

**Comment by SamDepardieu** [comment]
Fxied in #295
