### ISSUE TITLE
Discussion: Bringing deep_reference_parser into airflow

### ISSUE THREAD

**Issue by jdu** [wellcometrust/reach#282]
This is a continuation of a discussion started in the wellcome trust slack.

A quick recap:

We want to look at bringing the deep_reference_parser into reach, the discussion centers around whether that's done as an additional microservice or integration directly into airflow.

After the discussion on slack I think really the main point discussed was the start-up time for the deep_reference_parser and if there was any way to mitigate that by storing/loading the model from disk, S3 or similar.

**Comment by jdu** [comment]
As @hblanks mentioned in slack, because the airflow execution model is a batched periodic run, and we're not running it ad-hoc or continuosly, the resource usage and execution time is most likely a non-issue (I simply wanted to see if there was potential there to optimize it). We can look at how we optimize that with artefacts and data that don't need to change between runs further down the line if there are benefits to it, but because this isn't going to be used as part of a continuously running process or ad-hoc querying I don't think there's a strong case here for it to be split out into a completely separate service, though there may be something I'm missing if @ivyleavedtoadflax has some other constraints which might not be thinking about.

Because the airflow DAG is run periodically and it's not triggered as part of a user-facing synchronous interface where someone is waiting on a result, if the DAG takes significant time to run it won't/shouldn't negatively impact usage of the reach site itself or a reach users experience.

**Comment by ivyleavedtoadflax** [comment]
Cool this sounds good. Realistically I don't think I will be working on this until the first couple of weeks of December, so will revisit this then. But essentially, as I understand it I will just set up the logic as I would a batch job in my local machine, we can just implement this into a DAG?

**Comment by ivyleavedtoadflax** [comment]
I think we can close this now, as this is close to being merged in.
