### ISSUE TITLE
Search.py: Rewrite the download_CSV method

### ISSUE THREAD

**Issue by kristinenielsen** [wellcometrust/reach#337]
## Build plan

- Rewrite (and rename) DownloadCsv view to handle a POST request containing either all the selected items ids and a format type
- Change the output of the view to be the format specified in the request

## Estimate
1 day

## Acceptance criteria

- The user can get a json OR a csv file from a single UI button

**Comment by SamDepardieu** [comment]
I'm taking this in as I think last changes to the API might have broken the CSV download button without us noticing. Will also take this occasion to update the button to also throw json if needed 👍
