### ISSUE TITLE
LXML Errors in pdf parser

### ISSUE THREAD

**Issue by jdu** [wellcometrust/reach#343]
Some XML parsing errors are being suppressed in the PDF parser which is resulting in PDF policy documents not being included in the overall doc sets for various sources.

Issue has been traced to LXML being very strict and not allowing specific characters in attribute values unless they are explicitly escaped.

**Comment by kristinenielsen** [comment]
@TeriForey this might be one for you to pick up if you have some free time

**Comment by jdu** [comment]
This is fixed by #376
