### ISSUE TITLE
Refine user stories and scoping for 'Find Person feature' 

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#356]

**Comment by kristinenielsen** [comment]
@dd207 to review and close if done :)

**Comment by aoifespenge** [comment]
Work done on this to-date is: 
We've written out the hypotheses that explain experience design of the prototype to date: https://docs.google.com/document/d/16GlkuEoqUNq9Wd386wn1geC6A_2vY4NVdjRCVgNNpCI/edit#heading=h.2tqpzbckpp40

Liz has made some updates to the prototype based on the hypothesis.

**Comment by aoifespenge** [comment]
@dd207 we just need your input on what metadata to include in the prototype columns. Possible metadata is https://github.com/wellcometrust/reach/blob/master/reach/scraper/wsf_scraping/items.py

**Comment by dd207** [comment]
See #434
