### ISSUE TITLE
Various UI Items

### ISSUE THREAD

**Issue by jdu** [wellcometrust/reach#374]
This is just a list of UI items I came across this morning which seem counter-intuitive a bit and we should look at resolving

1. [x] The pagination in the results table should be mirrored at the bottom of the table -> You end up scrolling down to view items and having to scroll all the way back up to hit next.
1. [x] The links to open / access a policy document should open in a new tab/window as the page isn't preserved when you click back from the document.
1. [x] We should probably normalize the casing in the policy titles as some are right wonky
1. [x] Citations: The Authors column is a bit wonky, maybe we could show a link "Authors (# of authors)" that when hovered shows the full list of authors? Or trim the list with an ellipses and show the full list of authors when expanded in the expanded area?
1. [x] Show something other than "Undefined" which is javascript output in the Authors column in citations when we don't have the authors for a paper.
1. [x] Remove sort on authors column, we aren't ordering the authors in the value itself, so this won't really be a useful ordering mechanism and might actually not operate the way users would assume resulting in confusion.
1. [x] "Advanced Search Tips" is formatted as a link but doesn't do anything.
1. [x] The "api" link in the footer leads to a blank page, should route to the new API documentation
1. [x] On the search starting pages, the (?) icon isn't aligned with the "Advanced Search Tips" link
1. [ ] If a document/publication is missing a title, can we have formatting in the table to default to something like "Title Unavailable" so that the user can still click to open the document.
1. [ ] Can we set up a formatter for the Policy source so that instead of displaying "who_iris" we can display "WHO IRIS" and instead of "gov_uk" we display "Gov.co.uk" so it's a bit more reader friendly.
1. [x] Similar to missing title, instead of "undefined" under Authors in the citations table for the policies, can we show "Authors Unavailable"
1. [ ] Similar to authors column, if the title of a document is really long can we truncate it and show the full title inside the expanded area beneath and/or show the full title on hover of the link / text? Some of these titles cause a result row to take up a ton of vertical space causing you to scroll down pretty far to get the to the next row of results.

**Comment by SamDepardieu** [comment]
Thanks for the review, I'll do a wave of fixes this afternoon 👍

**Comment by jdu** [comment]
> Thanks for the review, I'll do a wave of fixes this afternoon 👍

Cool! Sorry for the bulk list of issues, just noticed these things while I was checking the UI was working after the DAG run.

**Comment by SamDepardieu** [comment]
Starting work on this

**Comment by SamDepardieu** [comment]
Not quite sure what to do/link to ` "Advanced Search Tips" is formatted as a link but doesn't do anything.`, So let's wait for some design or UX input on that.

**Comment by jdu** [comment]
> Not quite sure what to do/link to ` "Advanced Search Tips" is formatted as a link but doesn't do anything.`, So let's wait for some design or UX input on that.

^ @j-jaworski @IzziF @dd207 @aoifespenge

**Comment by jdu** [comment]
If we're not likely to have the functionality/content sorted out by alpha time for that link, we can just hide it from the UI as I'd rather the user see nothing there at all versus attempt clicking on it and forming a negative opinion of the site because they've interpreted it as a bug. To us it's an incomplete feature, but to a user, even a highly technical one, it will be interpeted as a bug.

**Comment by j-jaworski** [comment]
This is a hangover from the original original UX work that was done early last year. 100% we should hide the text link for now, as it would erode confidence and trust in the product. I suspect that a user need will emerge in the future to build more advanced searches, and we will need to offer some guidance for users. But this is not necessarily needed for Alpha.

**Comment by SamDepardieu** [comment]
So what are we doing with the associated tooltip? Hidden as well?

**Comment by j-jaworski** [comment]
Yeah as it doesn't make much sense with or without the text link, I would be tempted to hide it for now. It is not very accessible to useful information behind an unlabelled icon. If the content within that tooltip is crucial to users understanding the function of the page, then it should not be incorporated elsewhere in the design.
