### ISSUE TITLE
Search by phrase is no longer working

### ISSUE THREAD

**Issue by jdu** [wellcometrust/reach#381]
Can currently search for result based on a single word term, but using multiple terms or for instance an exact title of a document doesn't return any results.

For instance https://reach.staging.datalabs.wellcome.cloud/search/policy-docs?terms=High+quality+care+for+all returns no results although there is a policy document with that as a partial of the title.

**Comment by SamDepardieu** [comment]
I have a fix for it, but might want a bit more time to look into this, see if I can come with a better solution.

**Comment by SamDepardieu** [comment]
@dd207 opened another issue abotu this with this example:
```
Currently unable to retrieve results when searching for more than one word into the search bar for 'discover citations' and 'browse policy documents'.

Example:
Searching for publication title 'A study of typhoid fever in five Asian countries' results in error page.

Searching for a general topic 'typhoid' does retrieve matches for 'A study of typhoid fever in five Asian countries' but a user has to look through 80+ results to find that specific publication title.
```
