### ISSUE TITLE
Incorporate neural network based reference splitter

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [wellcometrust/reach#409]
Based on #317. Adding an issue just so it doesn't drop off the board.

**Comment by jdu** [comment]
I should hopefully be able to address this today, there's some configuration changes that need to happen and a merge to the release channel from master, once I get that done we can merge this back into master.

**Comment by jdu** [comment]
This is merged into master and deployed, a separate issue is being set up in datalabs-infra to tackle resource consumption / DAG failure #360
