### ISSUE TITLE
Unable to search by publication title in 'discover citations'

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#415]
@dd207 commented on [Tue Feb 11 2020](https://github.com/wellcometrust/datalabs/issues/580)

Errors with search by specific publication title. 

i.e. 'A study of typhoid in five asian countries' will retrieve 0 results and error page. User has to search by topic area 'typhoid' and then filter results.  

 We had thought this would be fixed via #403, but it's still an issue. 

After conversation with @SamDepardieu we've figured that it's probably due to limitations in Elastic Search and we'll have to  work out changing the database behind Reach. 

This is a consideration to take into account for testing next week @aoifespenge and something we need to prioritise fixing @jdu @SamDepardieu

**Comment by jdu** [comment]
@SamDepardieu  and I have had discussions about this previously and the problems we would likely face using Elastic as the backend for this. I didn't expect them to rear their head this quickly. The implementation for this should be fairly simple in terms of postgres, but I will get database schema designed and some triggers for managing tsvector data for searching against the data.

**Comment by jdu** [comment]
Also of note, if this is the case and we can look at moving to a different relational database we can probably remove #407 and use postgres as the backing store for the scrapers instead of SQLite.

**Comment by SamDepardieu** [comment]
Fixed 💪

**Comment by jdu** [comment]
Or @SamDepardieu can just fix it.

**Comment by SamDepardieu** [comment]
Yeah, we'd better change the backend DB anyway. I can't bear these search issues anymore, it's playing rollercoaster with my mind
