### ISSUE TITLE
Some of research publications with several citations are coming up as individual results instead of being nested together.

### ISSUE THREAD

**Issue by aoifespenge** [wellcometrust/reach#428]
Some of research publications with several citations are coming up as individual results instead of being nested together.
Search terms: A large proportion of p. falciparum isolates; Worldwide incidence of malaria in 2009

<img width="1258" alt="Screenshot 2020-02-12 at 19 03 46" src="https://user-images.githubusercontent.com/25910370/74441730-40dcd100-4e68-11ea-9052-59bf49ad1936.png">

**Comment by aoifespenge** [comment]
Assigning to Sam just as a flag, but putting this in backlog for @dd207 to process

**Comment by dd207** [comment]
Do we have an idea of why this is happening @SamDepardieu 

Will the architecture changes you are making address this?
