### ISSUE TITLE
Advanced search in Reach - kick off session 

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#434]
We're consolidating work related to API and 'Find Person' features (#355 and #356) to holistically think about Advanced Search within the product. 

We believe that users will want to expand and narrow the parameters of results they can retrieve from Reach. 

Specifically: 
a) searching for multiple publications at a time, and using different identifiers than titles (i.e. DOIs)
b) searching for specific influential people and organisations within the text of policy documents

We'll be doing an initial session bringing together data science, developers, design and user research to consolidate thinking on how we can meet these needs in the product.

**Comment by jdu** [comment]
I think one of the main decisions needs to be do we:

1. Implement advanced search query syntax to support this (KQL, Google Syntax, DDG Syntax, etc..)
2. Implement controls which allow adding filters dynamicallly, as well as preset toggle-able filters (source, type) and date range controls on the UI
3. Some combination of both

**Comment by dd207** [comment]
Outcomes of session:

Long term approach - revising our approach to search and prototyping a range of options. 

Short term approach - Jason to 'mock up' improvements that can be more easily implemented (systems feedback, table UI) 

Notes in document here: https://drive.google.com/drive/u/1/folders/1GSvlON90UA2hNpcXOGcSayi3k3H9XX4l
