### ISSUE TITLE
Remove unnecessary columns from CSV results in 'Discover Citations' and 'Browse Policy Docs' 

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#441]
Currently when users export results from Reach into a CSV, the CSV contains multiple rows that are unnecessary (e.g. similarity, match algo). See attached for example. 

We believe users will find the additional rows confusing and it will impair their ability to do further analysis on the results from Rea![Screenshot 2020-02-19 at 10.00.37.png](https://images.zenhubusercontent.com/5de5100384b91a10d0c5050f/81da2910-ffd2-4040-b385-861175c8008c)ch.

**Comment by kristinenielsen** [comment]
Needs research on which columns are most useful and then go into engineering to execute the tasks.

**Comment by dd207** [comment]
Hi @SamDepardieu can we do this issue next sprint also?

I'm assuming that once the postgres work is done you'll be able to modify the csv output more easily.

Let me know if this isn't correct/not possible.

**Comment by SamDepardieu** [comment]
Yup, that's true, once Postgres is done, exporting will be much simpler. Let's put that to next sprint too

**Comment by dd207** [comment]
Aware this this is being addressed now - so moving to 'in progress'
