### ISSUE TITLE
Rows on tables

### ISSUE THREAD

**Issue by j-jaworski** [wellcometrust/reach#461]
As a **user** I need to ** be able to quickly scan the results**
So that I can **assess the data for relevance**

A few things in this

- [x] Fixed height of table rows (truncate titles, author list etc) to ensure that all rows are the same height
- [x] When row is expanded the user should see the un-truncated title or author list
- [ ] Animate expandable rows open/close
- [x] Only one row open at a time (unless there is a user-centred reason not to)
- [x] Sub-header for expandable rows tweaked copy to "cited in the following policy documents"
- [x] Fixed width of columns to ensure users more easily see the data that will allow them to assess the relevance
- [ ]

**Comment by j-jaworski** [comment]
- [ ] I think having animation will hugely improve the usability on these
- [ ] Include active and static states for open/close chevrons
- [ ] Table border and row border E6E6E6
- [ ] Cell body style font-size: 14px; line-height: 24px;

**Comment by j-jaworski** [comment]
chevron should be `grey` by default 
chevron should be `bluegreen` when clicked on

Sorry dont have the color values to hand

**Comment by SamDepardieu** [comment]
Perfect thanks 👍
