### ISSUE TITLE
No results page 

### ISSUE THREAD

**Issue by j-jaworski** [wellcometrust/reach#465]
As a **user** I need to **know why a search has failed and how I can improve my search**
So that i can **get to the most relevant set of results for me**

No results page
https://zpl.io/a7NAD5j

Needs further exploration 
- What copy is best?
- can we suggest common spelling errors
- What advice is best for Reach users (the advice in the design is just a UX best practice)

**Comment by j-jaworski** [comment]
![Artboard.png](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/94d7b644-f196-4cfc-9e43-d77b1af21141)

- [ ] Hide this on ‘No results page’
- [ ] 'Search tips' Bold 16px
- [ ] Reduce line height on li

**Comment by SamDepardieu** [comment]
@j-jaworski The search suggestion part (`Did you mean to search for "Malaria"`) is strongly coupled to some non-implemented backend. Is there a way for me to replace it in the meantime, or should I remove it completely?

**Comment by j-jaworski** [comment]
@SamDepardieu Just remove it completely, for now – leaving the H1 and input field.
