### ISSUE TITLE
S3 scraper-results data update

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#47]
I found that the current scraper-results folder in S3 has not got very many JSON files in.

**Comment by SamDepardieu** [comment]
WHO had issues writing its json earlier this month. The scrape took too long, again, explaining why we have some missing files.

**Comment by SamDepardieu** [comment]
Though, it seems like our earlier changes to how the scraper downloads the files (tempsfiles rather than files) Made it possible for the scraper to write its data in S3 again. 

I'll leave this open to keep an eye on what happens.
