### ISSUE TITLE
Which groups to test Find Author Model against? 

### ISSUE THREAD

**Issue by aoifespenge** [wellcometrust/reach#477]
Proposed: 

Is the person an academic or not  (what's some examples of this 'not' group)
Gender (if possible) 
What country your name is your from (the following are assumed proxies for this)
- English versus non english 
- Length of names.... 
- Double-barrel versus single or middles names

**Comment by aoifespenge** [comment]
English versus non- English names is a bit tricky to find a dataset for

**Comment by lizgzil** [comment]
## `US/`

### 2000 census data - surnames and ethnicity

Frequently occuring surnames from the US 2000 census.

Tabulations of all surnames occurring 100 or more times in the Census 2000 returns are provided in the files listed below. The first link explains the methodology used for identifying and editing names data. The second link provides an Excel file of the top 1000 surnames. The third link provides zipped Excel and CSV (comma separated) files of the complete list of 151,671 names. The top ten surnames are:

`Top1000`: Top 1000 Names   

`app_c`: Surnames Occurring 100 or more times 

Downloaded from https://www.census.gov/topics/population/genealogy/data/2000_surnames.html

### 1990 census data - surnames and first names by gender.

Common names with frequency.

`dist.all.last.txt`
`dist.female.first.txt`
`dist.male.first.txt`

Downloaded from https://www2.census.gov/topics/genealogy/

## `UK/`

### Common first names by gender from 1904-1994

Historic lists of top 100 names for baby boys and girls for 1904 to 1994 at 10-yearly intervals.

`historicname_tcm77-254032.xls`

Downloaded from https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/datasets/babynamesenglandandwalestop100babynameshistoricaldata

## `World/`

### 

The list includes 4,250 first names and information on their respective count and proportions across six mutually exclusive racial and Hispanic origin groups.

`firstnames.xlsx`

Downloaded from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TYJKEZ

Tzioumis, Konstantinos (2018) Demographic aspects of first names, Scientific Data, 5:180025 [dx.doi.org/10.1038/sdata.2018.25].

## Bibliography

https://www.nature.com/articles/sdata201825#Tab5

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1797082/

Chen W, Petitti D B, Enger S. Limitations and Potential Uses of Census-Based Data on Ethnicity in a Diverse Community. Annals of Epidemiology. 2004;14:339–45. [PubMed] [Google Scholar]
