### ISSUE TITLE
Fairness definition for Find Person Feature

### ISSUE THREAD

**Issue by aoifespenge** [wellcometrust/reach#478]
We need to agree what fairness looks like for the Find Person model. Fairness can be defined in many ways depending on the context (and the philosophy, but we can use our principles to support this). 

Update:
Based on some recent reading and thinking here are two things to consider:

Do we care about individual fairness or group fairness? 
Do we care about fair treatment or fair outcome? 

I propose that in this case we are concerned about ensure that the model/systems performs the same disadvantaged groups as it does for the mainstream. So this means group fairness. 
Also its more important that we have a fair outcome for each author of the publication - the outcome is the likelihood of being picked up by the model, and this needs to be fair across groups.

**Comment by dd207** [comment]
Moving this to 'icebox' as we focus on releasing Reach
