### ISSUE TITLE
New table UI assets

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/reach#495]
The new table UI is basically done and just needs the following to be 100% complete:
- The circled "i" icon for the “Learn about these results” link
- A description of what the “Learn about these results” should do (tooltip? Link to the bottom of the page?)
- The asset for the loading indicator if you have it (I could probably make something, but it’d probably not be as good)
- I assumed the new sorting icon is the same arrow than the one on the mainpage, if it's not, I need the new asset too

**Comment by j-jaworski** [comment]
1. "i" Icon attached as .svg let me know if you would prefer a different format

![Info-icon.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/25e64de9-2ef3-45cc-b0be-11319b202c32)

2. "Learn about these results" should go to "How Reach works"

3. Loading indicator attached as a .svg and reference for animation here 

![Loading-indicator.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/8e846f05-499c-452b-a548-737422a8de38) 
https://material.io/components/progress-indicators

4.Sorting icons and arrows attached as .svg

![sorted-by-arrow-ascending.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/10d3ac08-8df2-437d-a86a-b8652e1607fa)

![double-chevron.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/130518d0-757d-4919-a659-d80494f292a0)

![down-chevron.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/18990891-c278-46a8-a6fc-5750d75e1dd3)

**Comment by SamDepardieu** [comment]
Hey @j-jaworski !
Just need one last icon. Can I get the 
![image](https://user-images.githubusercontent.com/6536364/80090427-67e60c00-8557-11ea-9331-73e657de3f16.png) icon in svg as well, please? :)

**Comment by j-jaworski** [comment]
new window icon 

![New-window.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/16090ca5-5387-4699-a29f-32c68e7d4b76)
