### ISSUE TITLE
Use PostgreSQL instead of ES in Reach web backend

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/reach#496]
# Rationale
At the moment, Reach is using Elasticsearch as its backend database. 

Elasticsearch is great to perform search operation in an optimised way, leading to better search speed into the huge number of publication we store.

This speed comes with a loss of customisation in our requests, that we currently want to get back to implement the new search features.

PostgreSQL offers good search speed and a better customisation level in the queries.

# Expected outcomes
- Reach is using a postgresql database as a backend

# Success criteria
- `search_api` relies on a postrges backend
- The JS search feature now parses pre-parsed dictionnaries, instad of opinionated ones to help with further possible changes
- The python backend builds queries to the database from both api calls and JS calls. These queries returns the same results

**Comment by dd207** [comment]
Can this be closed now @SamDepardieu ?

**Comment by SamDepardieu** [comment]
Sadly, not yet... I'm still fixing some stuff in there
