### ISSUE TITLE
Reach Alpha / Beta branding

### ISSUE THREAD

**Issue by j-jaworski** [wellcometrust/reach#521]
SVGs for new Reach Alpha and Reach Beta below

![Reach-beta-02.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/73fae487-b5fa-4a4d-85a1-f35b956118ef)

![Reach-alpha-01.svg](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/eb1c0e36-d05b-45b4-ad81-71805f56c638)

**Comment by dd207** [comment]
Hi @jdu, if you get to finish #443 early next week could you implement this one next?
