### ISSUE TITLE
Implement Postgres SQL search in 'Search Policy Docs' and 'Find Citations'

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#523]
Users need a consistent and quality search logic in the product.

Discussions with @jdu meant that postgres tsvector or tsquery is the recommended search logic to use across both aspects of the product.

https://www.postgresql.org/docs/10/datatype-textsearch.html

**Comment by dd207** [comment]
Can we work on this next sprint @SamDepardieu ?

**Comment by SamDepardieu** [comment]
Yes, I'm already including it so the big PSQL update will be complete when we release it

**Comment by dd207** [comment]
Thanks Sam - want to make sure it's tracked through the system 👍

**Comment by dd207** [comment]
@jdu I'm going to put this in sprint backlog as I know this is being implemented in amongst the other tasks on Postgres SQL
