### ISSUE TITLE
Inconsistency in feedback on the two search results pages and wrong email on one

### ISSUE THREAD

**Issue by aoifespenge** [wellcometrust/reach#553]
<img width="694" alt="Screenshot 2020-06-09 at 15 59 54" src="https://user-images.githubusercontent.com/25910370/84165073-24921f00-aa6b-11ea-9378-38300fdf0ea0.png">
<img width="662" alt="Screenshot 2020-06-09 at 15 59 13" src="https://user-images.githubusercontent.com/25910370/84165076-252ab580-aa6b-11ea-83d6-dcfe104ad78c.png">

The 'feedback' sections on each search results page are different. And one of them links to "engineering.datalabs@wellcome.ac.uk" is wrong email address. 
@dd207 What was the agreed content. Was it:

Can't find what you're looking for?

If something doesn’t look quite right, please get in touch with the team at reach@wellcome.ac.uk.

**Comment by jdu** [comment]
These emails shouldn't be displayed at all, should have a link to the contact page @SamDepardieu

**Comment by SamDepardieu** [comment]
Yup, will update that, I apparently missed that one when going over these

**Comment by dd207** [comment]
There is a ticket open #535  that covers all of these inconsistencies across the product. 

It's in the backlog for this sprint.
