### ISSUE TITLE
Implement Privacy and Terms of Use page in Reach 

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#562]
Implement Privacy and Terms of Use page in Reach

- [x] Include cookies information to Privacy and Terms of Use document (Dawn)
- [x] Use template[ here ](https://app.zeplin.io/project/58bd9edd507012294c189959/screen/5e592d56b54d1b673f400dd4/) to create page. Text for Privacy and Terms of use page found [here ](https://docs.google.com/document/d/1e3l9mWbFDlzKoTa_dkH_wpLtk4nuC1Gm/edit)
- [x] Link to Privacy and Terms of use page in the footer of Reach product 
<img width="843" alt="Screenshot 2020-06-15 at 09 55 37" src="https://user-images.githubusercontent.com/9429999/84638090-6d742880-aeee-11ea-94a3-cef04b8c3a08.png">

- [x]  Create cookies pop-up. We're using an automated consent banner for now https://www.websitepolicies.com/create/cookie-consent-banner

**Comment by SamDepardieu** [comment]
I'm on this now

**Comment by SamDepardieu** [comment]
All done here from a dev perspective. I'm now only waiting for the last copy changes 👍

**Comment by dd207** [comment]
Hi Sam, thanks there are just a couple of minor things. 

The privacy statement here should be hyperlinked:
<img width="716" alt="Screenshot 2020-06-16 at 11 25 35" src="https://user-images.githubusercontent.com/9429999/84763819-b5657f00-afc4-11ea-8f3f-198a299d3b0b.png">

The words **'Creative Commons Attribution 2.0 (opens in a new tab'** should link to this page online: https://creativecommons.org/licenses/by/2.0/uk/
<img width="739" alt="Screenshot 2020-06-16 at 11 24 54" src="https://user-images.githubusercontent.com/9429999/84763872-c7472200-afc4-11ea-8e01-68efd643e6b2.png">
