### ISSUE TITLE
Typos and text changes in Reach 

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#569]
Danil did some QA for Reach and found a couple of typos. He's also asked us to be more specific about the meaning of alpha in the 'About Us' page for Reach. 

- [x] More info on the meaning of alpha on the 'About Us' page. 

Can we add the following text under the 'What is the focus of Reach' heading? :

"Reach is an ‘alpha’ product stage meaning that this is our first release to the public. While we are continually developing and improving Reach there could be some inaccuracies in search results or analysis"

<img width="446" alt="Screenshot 2020-06-17 at 13 59 52" src="https://user-images.githubusercontent.com/9429999/84901410-588cc600-b0a3-11ea-9f62-1fb18aec746b.png">

- [x] Making clear that we source *publicly available* policy documents in the text of the product 

Change "policy documents" to " **publicly available policy documents** " in this text

<img width="469" alt="Screenshot 2020-06-17 at 14 12 19" src="https://user-images.githubusercontent.com/9429999/84902559-def5d780-b0a4-11ea-8817-ba3ada916d5f.png">

And here... Change "policy documents" to " **publicly available policy documents** " in this text

<img width="853" alt="Screenshot 2020-06-17 at 14 09 32" src="https://user-images.githubusercontent.com/9429999/84902906-50358a80-b0a5-11ea-8ffb-2f38ed90660e.png">

And finally here... Change "policy documents" to " **publicly available policy documents** " in this text

<img width="426" alt="Screenshot 2020-06-17 at 14 08 50" src="https://user-images.githubusercontent.com/9429999/84903055-81ae5600-b0a5-11ea-8064-d2c5f151b37d.png">

- [ ] We need to link to the Wellcome Data Labs page on the corporate website in places (https://wellcome.ac.uk/about-us/teams/wellcome-data-labs) 

'Data Labs' link in footer should refer to [here](https://wellcome.ac.uk/about-us/teams/wellcome-data-labs) throughout product 

<img width="322" alt="Screenshot 2020-06-17 at 14 19 57" src="https://user-images.githubusercontent.com/9429999/84903321-d81b9480-b0a5-11ea-8c79-02ed6f0d321f.png">

Data Labs highlighted here should link to [ here](https://wellcome.ac.uk/about-us/teams/wellcome-data-labs)

<img width="604" alt="Screenshot 2020-06-17 at 14 19 41" src="https://user-images.githubusercontent.com/9429999/84903641-42ccd000-b0a6-11ea-8736-403b5397707b.png">

- [x] Spelling mistake - 'community' 

<img width="497" alt="Screenshot 2020-06-17 at 14 25 01" src="https://user-images.githubusercontent.com/9429999/84903813-77d92280-b0a6-11ea-9886-3d93b5f52a70.png">

**Comment by SamDepardieu** [comment]
@dd207 Yup, on it right now.
