### ISSUE TITLE
s3 and DB scraped data are not the same

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/reach#57]
Running this in the database
```sql
select
	provider.name,
	count(*)
from publication
inner join provider on provider.id=publication.id_provider
group by 1
```
returns
<img width="224" alt="screen shot 2019-02-12 at 4 53 05 pm" src="https://user-images.githubusercontent.com/4975761/52652804-af4e2280-2ee6-11e9-9032-38e66eae923d.png">
 but at the same time running `wc -l ../data` in the latest scraped jsons returns
<img width="229" alt="screen shot 2019-02-12 at 4 53 24 pm" src="https://user-images.githubusercontent.com/4975761/52652876-cbea5a80-2ee6-11e9-9ba5-3d6c427333d1.png">
The numbers are quite different in all organisations. Is that a feature or a bug?

**Comment by SamDepardieu** [comment]
Not an issue anymore as we don't use any database. Closing this.
