### ISSUE TITLE
'Find Citations' - results are showing publications with 0 citations in policy documents 

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#572]
Searching for a generic term 'mice' gives me only publications with 0 citation matches. 

This is high priority - can we investigate as soon as poss? 

<img width="1251" alt="Screenshot 2020-06-18 at 11 24 48" src="https://user-images.githubusercontent.com/9429999/85009568-8aab3000-b156-11ea-98c4-14a494add081.png">

**Comment by SamDepardieu** [comment]
This is fixed
