### ISSUE TITLE
Fix API page 

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#576]
There seems to be a formatting problem with the API page in Reach - see below. 

@SamDepardieu mentioned that this could be a problem with static files. 

We're demoing Reach to the rest of Digital on Friday - can we fix this before then. 

<img width="1001" alt="Screenshot 2020-06-24 at 10 54 15" src="https://user-images.githubusercontent.com/9429999/85534336-2d592800-b609-11ea-9809-5c30019ee14b.png">

**Comment by SamDepardieu** [comment]
This is fixed
