### ISSUE TITLE
Fix nb_documents calculation

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#66]
Currently in line 111 of [refparser.py](https://github.com/wellcometrust/policytool/blob/master/refparse.py) we have 
`nb_documents = sum(scraper_file['sections'].notnull())`
this should be
`nb_documents = len(list(transform_scraper_file(scraper_file)))`

 Not sure why, but I found that the old calculation gave a number much higher than the actual number of documents.

**Comment by nsorros** [comment]
The problem with this is that it ignores the fact that transform_scraper_file is a generator and it enforces all the items to be read which is not ideal. I will leave it open because maybe there is another solution to the problem which i cannot think now

**Comment by lizgzil** [comment]
fixed. this is now added to iteratively in the loop of processing the documents
