### ISSUE TITLE
output csv formats occassionally incorrect

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#79]
I found that when I came to merge all the `_all_match_data.csv`'s some of them threw up errors since the output wasn't in the correct format.

Looking into one of these : `dc1b4f8cb79f432a58490dc75866bee6_all_match_data.csv`, the file looks like:
![screenshot 2019-02-20 at 10 11 34](https://user-images.githubusercontent.com/15956065/53084033-ee3c3380-34f7-11e9-8d4a-7a15619273c7.png)

So saving special characters (in this case bullet points I think) seems to mess up in perhaps line 178 of [`refparse.py`](https://github.com/wellcometrust/policytool/blob/master/refparse.py), or perhaps earlier.

Out of 7799 files for both the `_all_match_data.csv` and `_predicted_reference_structures.csv` type of files (i.e. there were 7799 files of each type, 15,598 in total), these read errors happened for 2 `_all_match_data.csv` files (both who_iris), and 5 `_predicted_reference_structures.csv` files (2 who_iris, 3 gov_uk). 

I very commonly have issues saving large amounts of text (since the likelihood of a special character coming up is higher) to csv using pandas. I've tried the encoding parameter. Would quite like to discuss why this issue seems to come up so much and how to work around it.

The momentary fix for this is in `merge_results.py` to replace
```
match_data = pd.read_csv(match_csv_name)
    if not match_data.empty:
       all_matches.append(match_data)
```
with
```
try:
   match_data = pd.read_csv(match_csv_name)
   if not match_data.empty:
        all_matches.append(match_data)
except:
   print('Read csv issue for file {}'.format(match_csv_name))
```

## Solution discussed offline:

Since sometimes the output of predicting and matching the references can involve special characters like `\n` and `\r` in the same document, `to_csv` can sometimes not write the correct information. By writing to a json this issue should be solved without having to loose any information from the text.

- [ ] Therefore in `refparse.py` :
```
predicted_reference_structures.to_csv(
    os.path.join(
        output_dir,
        f"{doc.id}_{settings.PREF_REFS_FILENAME}"
        )
    )
all_match_data.to_csv(
    os.path.join(
        output_dir,
        f"{doc.id}_{settings.MATCHES_FILENAME}"
        )
    )
```
should be changed to 
```
predicted_reference_structures.to_json(
    os.path.join(
        output_dir,
        f"{doc.id}_{settings.PREF_REFS_FILENAME}"
        ),
        orient='records',
        lines=True
    )
all_match_data.to_json(
    os.path.join(
        output_dir,
        f"{doc.id}_{settings.MATCHES_FILENAME}"
        ),
        orient='records',
        lines=True
    )
```

- [ ] Parts of `merge_results.py` will also need changing after this is done. Reading the JSON files will also need the `orient='records', lines=True` arguments.

- [ ] Furthermore, trialling this out revealed an issue in `fuzzymatch.py`. When we concatenate the parts that make up `match_data` we should drop the index since the resulting dataframe contains 3 columns called index and this causes a problem when saving to JSON.

**Comment by hblanks** [comment]
@lizgzil  - chances are we should spend a little time figuring out how text is being encoded into these files, and whether we should be using pandas or the csv module to read & write to them.

Is there a good time today or tomorrow to look into this with you?

**Comment by lizgzil** [comment]
> @lizgzil - chances are we should spend a little time figuring out how text is being encoded into these files, and whether we should be using pandas or the csv module to read & write to them.
> 
> Is there a good time today or tomorrow to look into this with you?

that would be great. anytime after 2.30 today would be good for me. @peter337 are you free then too?

**Comment by peter337** [comment]
Yup, sounds good to me

**Comment by peter337** [comment]
@lizgzil @hblanks We got a time for this afternoon?

**Comment by nsorros** [comment]
What was the error? And did you end up resolving this?

**Comment by hblanks** [comment]
We resolved it, but I don't think @lizgzil  has pushed a PR for it yet.

**Comment by hblanks** [comment]
In short, we were using CSV for data that contained various kinds of whitespace. We resolved it by switching to using JSON lines.

**Comment by nsorros** [comment]
👍

**Comment by lizgzil** [comment]
Yep I haven't worked on changing this to a JSON save at all.

FYI that I will update the info here with how we discussed we would solve it

**Comment by peter337** [comment]
Just to add to the list of concerns surrounding .csv files, Liz recently discovered an error that can occur when looking at Research Fish publications in Excel.
Some publication titles, for whatever reason, start with mathematical operators e.g. '-5C temperatures...'. When this is opened in Excel, due to the leading operator it tries to interpret these titles as formula, inevitably fails, and then throws a #NAME! error. If you then save the file, the error is saved instead of the publication title, losing it.
Possibly a risk worth bearing in mind, even with the switch the .json files, as Dimensions returns .csv files.

**Comment by lizgzil** [comment]
i think merger_results is irrelevant now
